// src/components/TwoFAModal/TwoFAModal.jsx

import { useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { 
  Shield, 
  X, 
  Smartphone, 
  QrCode, 
  Key, 
  CheckCircle, 
  ChevronDown,
  Info,
  Copy,
  Clock,
  AlertCircle,
  ShieldCheck,
  WifiOff,
  Zap,
  Download,
  Apple,
  Smartphone as AndroidIcon,
  Lock,
  ArrowLeft,
  ArrowRight
} from "lucide-react";
import "./twofa-modal.css";

// [FIXED] Import bind service untuk 2FA, bukan auth
import { bind } from "../../services/api";

// ── Apps ─────────────────────────────────────────────
const APPS = [
  {
    name: "Google Authenticator",
    icon: Smartphone,
    ios: "https://apps.apple.com/app/google-authenticator/id388497605",
    android: "https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2",
  },
  {
    name: "Microsoft Authenticator",
    icon: ShieldCheck,
    ios: "https://apps.apple.com/app/microsoft-authenticator/id983156458",
    android: "https://play.google.com/store/apps/details?id=com.azure.authenticator",
  },
];

// ── How It Works Data ────────────────────────────────
const HOW_IT_WORKS_STEPS = [
  {
    icon: Download,
    title: "Install App",
    description: "Download an authenticator app from App Store or Google Play"
  },
  {
    icon: QrCode,
    title: "Scan QR Code",
    description: "Use the app to scan the QR code displayed on screen"
  },
  {
    icon: Key,
    title: "Enter Code",
    description: "Enter the 6-digit code generated by the app to verify"
  },
  {
    icon: Clock,
    title: "Auto-generate",
    description: "Codes refresh every 30 seconds for maximum security"
  }
];

// ── Steps ────────────────────────────────────────────
function Steps({ current }) {
  return (
    <div className="tfa-steps">
      <div className="tfa-stepper">
        <div className={`tfa-step ${current >= 1 ? "tfa-step--active" : ""} ${current > 1 ? "tfa-step--done" : ""}`}>
          <div className="tfa-step-circle">
            {current > 1 ? <CheckCircle size={18} /> : "1"}
          </div>
          <span className="tfa-step-label">Setup</span>
        </div>

        <div className="tfa-step-line" />

        <div className={`tfa-step ${current >= 2 ? "tfa-step--active" : ""} ${current > 2 ? "tfa-step--done" : ""}`}>
          <div className="tfa-step-circle">
            {current > 2 ? <CheckCircle size={18} /> : "2"}
          </div>
          <span className="tfa-step-label">Scan</span>
        </div>

        <div className="tfa-step-line" />

        <div className={`tfa-step ${current >= 3 ? "tfa-step--active" : ""}`}>
          <div className="tfa-step-circle">3</div>
          <span className="tfa-step-label">Verify</span>
        </div>
      </div>
    </div>
  );
}

// ── How It Works Component ───────────────────────────
function HowItWorks() {
  const [isExpanded, setIsExpanded] = useState(false);

  return (
    <div className="tfa-how-it-works">
      <button 
        className="tfa-how-it-works-toggle"
        onClick={() => setIsExpanded(!isExpanded)}
      >
        <Info size={16} className="tfa-how-icon" />
        <span>How Two-Factor Authentication Works</span>
        <ChevronDown size={16} className={`tfa-how-arrow ${isExpanded ? 'expanded' : ''}`} />
      </button>
      
      {isExpanded && (
        <div className="tfa-how-content">
          <div className="tfa-how-grid">
            {HOW_IT_WORKS_STEPS.map((step, idx) => {
              const IconComponent = step.icon;
              return (
                <div key={idx} className="tfa-how-card">
                  <div className="tfa-how-card-icon">
                    <IconComponent size={28} strokeWidth={1.5} />
                  </div>
                  <div className="tfa-how-card-title">{step.title}</div>
                  <div className="tfa-how-card-desc">{step.description}</div>
                </div>
              );
            })}
          </div>
          
          <div className="tfa-how-benefits">
            <div className="tfa-benefit-item">
              <ShieldCheck size={20} className="tfa-benefit-icon" />
              <div>
                <strong>Enhanced Security</strong>
                <p>Protects your account even if your password is compromised</p>
              </div>
            </div>
            <div className="tfa-benefit-item">
              <WifiOff size={20} className="tfa-benefit-icon" />
              <div>
                <strong>Works Offline</strong>
                <p>Authenticator apps work without internet connection</p>
              </div>
            </div>
            <div className="tfa-benefit-item">
              <Zap size={20} className="tfa-benefit-icon" />
              <div>
                <strong>Quick Setup</strong>
                <p>Takes less than 2 minutes to secure your account</p>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// ── Component ────────────────────────────────────────
export default function TwoFAModal({ open, onClose, onSuccess }) {
  const overlayRef = useRef(null);
  const inputRefs = useRef([]);

  const [step, setStep] = useState(1);
  const [qr, setQr] = useState(null);
  const [digits, setDigits] = useState(["","","","","",""]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState(false);
  const [secretKey, setSecretKey] = useState("");

  // ── Load QR ── [FIXED] menggunakan bind.setup2FA
  useEffect(() => {
    if (!open) return;

    setStep(1);
    setQr(null);
    setDigits(["","","","","",""]);
    setError("");
    setSuccess(false);
    setSecretKey("");

    setLoading(true);

    bind.setup2FA()
      .then((res) => {
        if (res?.qr) {
          setQr(res.qr);
          if (res?.secret) setSecretKey(res.secret);
        }
        else setError("Failed to generate QR code.");
      })
      .catch((err) => {
        console.error("2FA Setup Error:", err);
        setError(err?.message || "Failed to initialize 2FA.");
      })
      .finally(() => setLoading(false));
  }, [open]);

  // ── Overlay click ─────────────────────────────────
  const handleOverlay = (e) => {
    if (e.target === overlayRef.current) onClose();
  };

  // ── OTP input ─────────────────────────────────────
  const handleChange = (i, v) => {
    const val = v.replace(/\D/g, "").slice(-1);
    const next = [...digits];
    next[i] = val;
    setDigits(next);

    if (val && i < 5) inputRefs.current[i + 1]?.focus();
  };

  const handleKeyDown = (i, e) => {
    if (e.key === 'Backspace' && !digits[i] && i > 0) {
      inputRefs.current[i - 1]?.focus();
    }
  };

  const handleVerify = async () => {
    const code = digits.join("");
    if (code.length !== 6) return;

    setLoading(true);
    setError("");

    try {
      // [FIXED] menggunakan bind.enable2FA
      await bind.enable2FA(code);
      setSuccess(true);

      setTimeout(() => {
        onSuccess?.();
        onClose();
      }, 1500);
    } catch (e) {
      setError(e?.message || "Invalid verification code. Please try again.");
      setDigits(["","","","","",""]);
      inputRefs.current[0]?.focus();
    } finally {
      setLoading(false);
    }
  };

  const copySecretKey = () => {
    if (secretKey) {
      navigator.clipboard.writeText(secretKey);
      // Optional: Show toast notification
    }
  };

  if (!open) return null;

  return createPortal(
    <div className="tfa-overlay" ref={overlayRef} onClick={handleOverlay}>
      <div className="tfa-modal">

        {/* Header */}
        <div className="tfa-header">
          <div className="tfa-header-left">
            <div className="tfa-header-icon">
              <Lock size={20} strokeWidth={1.5} />
            </div>
            <div className="tfa-header-text">
              <span className="tfa-title">Two-Factor Authentication</span>
              <span className="tfa-subtitle">Add an extra layer of security</span>
            </div>
          </div>

          <button className="tfa-close" onClick={onClose}>
            <X size={18} />
          </button>
        </div>

        {!success && <Steps current={step} />}

        {/* STEP 1 */}
        {!success && step === 1 && (
          <div className="tfa-body">
            <p className="tfa-instruction">
              Protect your account with 2FA. Choose an authenticator app to get started.
            </p>

            <div className="tfa-apps-grid">
              {APPS.map(app => {
                const IconComponent = app.icon;
                return (
                  <div key={app.name} className="tfa-app-card">
                    <div className="tfa-app-icon">
                      <IconComponent size={28} strokeWidth={1.5} />
                    </div>
                    <div className="tfa-app-name">{app.name}</div>
                    <div className="tfa-app-links">
                      <a href={app.ios} target="_blank" rel="noopener noreferrer" aria-label="App Store">
                        <Apple size={16} />
                      </a>
                      <a href={app.android} target="_blank" rel="noopener noreferrer" aria-label="Google Play">
                        <AndroidIcon size={16} />
                      </a>
                    </div>
                  </div>
                );
              })}
            </div>

            <HowItWorks />

            <div className="tfa-actions">
              <button className="tfa-btn-ghost" onClick={onClose}>Cancel</button>
              <button className="tfa-btn-primary" onClick={() => setStep(2)}>
                Continue <ArrowRight size={16} />
              </button>
            </div>
          </div>
        )}

        {/* STEP 2 */}
        {!success && step === 2 && (
          <div className="tfa-body">
            <p className="tfa-instruction">
              Open your authenticator app and scan this QR code
            </p>

            <div className="tfa-qr-wrap">
              {loading ? (
                <div className="tfa-qr-skeleton" />
              ) : qr ? (
                <>
                  <img src={qr} className="tfa-qr-img" alt="2FA QR Code" />
                  {secretKey && (
                    <button className="tfa-copy-secret" onClick={copySecretKey}>
                      <Copy size={14} /> Copy Key
                    </button>
                  )}
                </>
              ) : (
                <div className="tfa-error-state">
                  <AlertCircle size={32} />
                  <p>{error || "Failed to load QR code"}</p>
                </div>
              )}
            </div>

            <div className="tfa-tip">
              <Info size={14} className="tfa-tip-icon" />
              <span>Can't scan? Click "Copy Key" to enter manually into your authenticator app</span>
            </div>

            <div className="tfa-actions">
              <button className="tfa-btn-ghost" onClick={() => setStep(1)}>
                <ArrowLeft size={16} /> Back
              </button>
              <button className="tfa-btn-primary" onClick={() => setStep(3)}>
                I've Scanned the Code
              </button>
            </div>
          </div>
        )}

        {/* STEP 3 */}
        {!success && step === 3 && (
          <div className="tfa-body">
            <p className="tfa-instruction">
              Enter the 6-digit verification code from your app
            </p>

            <div className="tfa-otp-row">
              {digits.map((d, i) => (
                <input
                  key={i}
                  ref={(el) => (inputRefs.current[i] = el)}
                  className="tfa-otp-input"
                  type="text"
                  inputMode="numeric"
                  maxLength={1}
                  value={d}
                  onChange={(e) => handleChange(i, e.target.value)}
                  onKeyDown={(e) => handleKeyDown(i, e)}
                />
              ))}
            </div>

            <div className="tfa-code-timer">
              <Clock size={14} className="tfa-timer-icon" />
              <span>Code refreshes every 30 seconds</span>
            </div>

            {error && (
              <div className="tfa-error">
                <AlertCircle size={14} />
                <span>{error}</span>
              </div>
            )}

            <div className="tfa-actions">
              <button className="tfa-btn-ghost" onClick={() => setStep(2)}>
                <ArrowLeft size={16} /> Back
              </button>
              <button
                className="tfa-btn-primary"
                onClick={handleVerify}
                disabled={digits.join("").length !== 6 || loading}
              >
                {loading ? "Verifying..." : "Enable 2FA"}
                {!loading && <ArrowRight size={16} />}
              </button>
            </div>
          </div>
        )}

        {/* SUCCESS */}
        {success && (
          <div className="tfa-body tfa-body--success">
            <div className="tfa-success-ring">
              <CheckCircle size={36} strokeWidth={1.5} />
            </div>
            <p className="tfa-success-title">2FA Enabled Successfully!</p>
            <p className="tfa-success-message">Your account is now more secure</p>
            <div className="tfa-success-tip">
              <Shield size={14} />
              <span>Save your backup codes in a safe place</span>
            </div>
          </div>
        )}

      </div>
    </div>,
    document.body
  );
}